export const EMIT_CONNECTED = "EMIT_CONNECTED";
export const EMIT_INITIALIZE_DATA = "EMIT_INITIALIZE_DATA";
export const EMIT_ADD_DATA = "EMIT_ADD_DATA";
export const EMIT_ERROR = "EMIT_ERROR";
export const EMIT_RECONNECT = "EMIT_RECONNECT";
