export const ORDERS_CONNECTING = "ORDERS_CONNECTING";
export const ORDERS_CONNECTED = "ORDERS_CONNECTED";
export const ORDERS_INITIALIZE = "ORDERS_INITIALIZE";
export const ORDERS_ADD = "ORDERS_ADD";
export const ORDERS_ERROR = "ORDERS_ERROR";
